name: Determine responsibilities for the week

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  post-to-Discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord post action step
        id: discord
        uses: AAU-Dat/automate-team-responsibilities@v2.0
        with:
          team: '["Christoffer', "Daniel", "Gustav", "Jamie", "Lars", "Sebastian"]'
          responsibilities: '[{"name": "Scrum Master", "random": false}, {"name": "Second Scrum Master", "random": true}]'
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
